### ISSUE TITLE
Rename `isNullOrUndefined` to `isNullish`

### ISSUE THREAD

**Issue by pizzafox** [sapphire-project/utilities#30]
Breaking change.

https://github.com/sapphire-project/utilities/blob/b7ea1349f26f7a864a12b31e84d700a3e1c22ddc/packages/utilities/src/lib/isNullOrUndefined.ts#L5

The term "nullish" should be used instead of "`null` or `undefined`". This conforms to the language use in the [ECMAScript:copyright: 2020 Language Specification](https://www.ecma-international.org/ecma-262/#sec-intro).

> “nullish” values (**`null`** or **`undefined`**)

**Comment by kyranet** [comment]
ngl, I made a `isNullish` function (as well as a `Nullish` type) because it sounded cool.

Now it turns out they exist per spec, lmao.

**Comment by Favna** [comment]
Rather than renaming it we should provide an alias. 

```
export const isNullish = isNullOrUndefined
```

That way it's a minor feature update rather than a major breaking change update.

**Comment by pizzafox** [comment]
I suggest the following:

1. Rename `isNullOrUndefined` to `isNullish`
2. Create a new exported function called `isNullOrUndefined` that is

```ts
/**
 * @deprecated
 */
export function isNullOrUndefined(value: unknown): value is undefined | null {
  process.emitWarning(
    'isNullOrUndefined was renamed to isNullish. ',
    'DeprecationWarning'
  );

  return isNullish(value);
}
```

**Comment by kyranet** [comment]
That would work, if it weren't for the fact we're bundling for web too.

**Comment by pizzafox** [comment]
```ts
/**
 * @deprecated
 */
export function isNullOrUndefined(value: unknown): value is undefined | null {
  const deprecationMessage = "isNullOrUndefined was renamed to isNullish.";

  if (typeof process === "undefined") {
    // Browser
    const DeprecationWarning = Error;
    
    console.warn(new DeprecationWarning(deprecationMessage));
  } else {
    // Node.js
    process.emitWarning(deprecationMessage, "DeprecationWarning");
  }

  return isNullish(value);
}
```
I'm not familiar with your build system, but if you define a global like `__BROWSER__` you could use that instead of explicitly checking for `process`.

Also, if deprecating things cross-platform is going to happen more than once, consider writing a `deprecate(message: string): void` function that works everywhere.

**Comment by Favna** [comment]
The better way would probably be switching to a rollup wrapper/bundler like tsdx (https://github.com/formium/tsdx). They natively support the `__DEV__` expression as well as prod-only warning functions. For example I have an tinyWarning (based on https://github.com/alexreardon/tiny-warning) function in react-if (https://github.com/romac/react-if/blob/master/src/tinyWarning.ts) that logs when `NODE_ENV` is **not** `'production'` but does not log when it is.

And since this just uses `console.warn` it will work in both browsers and NodeJS

**Comment by pizzafox** [comment]
I used tsdx in a bunch of my packages and it's very cool. That's actually where I got the thought of build-time constants like `__DEV__`! I'd suggest using it, but it doesn't scale very well for large projects. For an ecosystem like Sapphire a custom solution is more work initially but is probably better for developer experience.

**Comment by pizzafox** [comment]
Well this issue was an interesting discussion.
What's the conclusion? Rename the function? New build system? Deprecation util?

I'd totally be up for implementing any of these. Let me know what the decision is.
