### ISSUE TITLE
request(time-utilities): Add formatting options for duration

### ISSUE THREAD

**Issue by Nytelife26** [sapphire-project/utilities#34]
Currently, the duration formatter only supports changing the name of the units. 
e.g.
`DurationFormatter(TIMES).format(11101000) => 3 hours 5 minutes 1 second`

For versatility purposes and to increase the use cases of the package, it would be better to support format strings with substitution, similar to how date formatting is done with the built-in Date object.
e.g.
`DurationFormatter("%h:%m:%s").format(11101000) => 03:05:01`

**Comment by Nytelife26** [comment]
If these are desired changes, I can begin working on them myself. Just let me know.

**Comment by pizzafox** [comment]
Can [existing Node.js APIs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) be used instead?

**Comment by kyranet** [comment]
```ts
import { Timestamp } from '@sapphire/time-utilities';

const ts = new Timestamp('HH:mm:ss');
console.log(ts.displayUTC(1500)); // -> 00:00:01
console.log(ts.displayUTC(65000)); // -> 00:01:05
console.log(ts.displayUTC(9593000)); // -> 02:39:53
```
